defaults:
  - hydra: custom
  
description: 'Drawing'

#path: outputs/2021-03-12/23-48-26/
path: checkpoints/first/
ckpt: first_checkpoint-10000.pt
dataloader: validation

data:
  train:
    query:
      root: /home/vladimir/Diploma/coco/val2017
      annotation: /home/vladimir/Diploma/coco/annotations/person_keypoints_val2017.json

    support:
      root: /home/vladimir/Diploma/coco/val2017
      annotation: /home/vladimir/Diploma/coco/annotations/person_keypoints_val2017.json
      
  validation:
    query:
      root: /home/vladimir/Diploma/coco/val2017
      annotation: /home/vladimir/Diploma/data/q_transferring_test_anns.json

    support:
      root: /home/vladimir/Diploma/coco/val2017
      annotation: /home/vladimir/Diploma/data/s_transferring_test_anns.json

