defaults:
  - hydra: custom
  - data_path: theta
  - dataset: dataset

description: ''

n_steps: 40000
bs: 32
desired_bs: 32
k_shot: 3
device: cuda:0
amp: false

metrics:
  - type: metrics.AveragePrecision
  - type: metrics.Recall
  - type: metrics.Precision
  - type: metrics.IoU

hooks:
  - type: callbacks.LogCallback
    frequency: 20

  - type: callbacks.ValidationCallback
    frequency: 300

  - type: callbacks.TensorBoardCallback
    frequency: 20

  - type: callbacks.SaveCheckpointCallback
    frequency: 5000

model:
  type: models.prikol.PrikolNet
  backbone:
    type: models.backbone.resnet_backbone
    name: resnet50
    pretrained: true
    trainable_layers: 3
    returned_layer: 4
    stride: 32
  # transformer
  embd_dim: 2048
  n_head: 4
  attn_pdrop: 0.1
  resid_pdrop: 0.1
  embd_pdrop: 0.1
  n_layer: 1
  out_dim: 5

optimizer:
  type: torch.optim.Adam
  lr: 3e-7

loss:
  type: loss.CustomYOLOLoss
  bbox_criterion:
    type: loss.EIoULoss
    reduction: sum
  conf_criterion:
    type: torch.nn.BCEWithLogitsLoss
  lambda_noobj: 1
  lambda_bbox: 1
  lambda_obj: 7
  img_size: ${data.input_size}
  grid_size: [10, 10]

scheduler:
  type: torch.optim.lr_scheduler.StepLR
  step_size: 1000
  gamma: 1.

data:
  bbox_format: coco
  input_size: [320, 320]
  train_transforms:
    - type: albumentations.Resize
      height: ${data.input_size.0}
      width: ${data.input_size.1}
    - type: albumentations.Normalize
    - type: albumentations.pytorch.transforms.ToTensorV2

  val_transforms:
    - type: albumentations.Resize
      height: ${data.input_size.0}
      width: ${data.input_size.1}
    - type: albumentations.Normalize
    - type: albumentations.pytorch.transforms.ToTensorV2

  train_dataset:
    - ${megapixel_mnist_train}

  validation_dataset:
    - ${megapixel_mnist_val_novel_cats}
    - ${megapixel_mnist_val_train_cats}
