defaults:
  - hydra: custom

device: cpu
bs: 1
description: 'Drawing'

path: outputs/2021-04-01/12-52-58/
ckpt: checkpoint-250.pt
dataloader: validation

data:
  train:
    query:
      root: /data/megapixel_mnist/train
      annotations: /data/megapixel_mnist/annotations/train.json

    support:
      root: /data/megapixel_mnist/train
      annotations: /data/megapixel_mnits/annotations/train.json
      
  validation:
    query:
      root: /data/megapixel_mnist/train_val
      annotations: /data/megapixel_mnist/annotations/val_train_cats.json

    support:
      root: /data/megapixel_mnist/train_val
      annotations: /data/megapixel_mnist/annotations/val_train_cats.json

