defaults:
  - hydra: custom
  - data_path: local
  - dataset: dataset

description: ''

n_steps: 250
bs: 2
k_shot: 3
device: cpu

metrics:
  - type: metrics.Recall
  - type: metrics.Precision

hooks:
  - type: callbacks.ValidationCallback
    frequency: 30

  - type: callbacks.LogCallback
    frequency: 20

  - type: callbacks.TensorBoardCallback
    frequency: 20

  - type: callbacks.SaveCheckpointCallback
    frequency: 50000

model:
  type: models.prikol.PrikolNet
  # backbone
  backbone_name: resnet50
  backbone_pretrained: true
  backbone_trainable_layers: 3
  backbone_returned_layers: 4
  backbone_stride: 32
  # transformer
  embd_dim: 2048
  n_head: 4
  attn_pdrop: 0
  resid_pdrop: 0
  embd_pdrop: 0
  n_layer: 1
  out_dim: 1

optimizer:
  type: torch.optim.Adam
  lr: 0.0003
loss:
  type: torch.nn.BCEWithLogitsLoss
  pos_weight:
    type: torch.tensor
    data: 1

scheduler:
  type: torch.optim.lr_scheduler.StepLR
  step_size: 1000
  gamma: 0.9

data:
  bbox_format: coco
  input_size: [320, 320]
  train_transforms:
    - type: albumentations.Resize
      height: ${data.input_size.0}
      width: ${data.input_size.1}
    - type: albumentations.Normalize
    - type: albumentations.pytorch.transforms.ToTensorV2

  val_transforms:
    - type: albumentations.Resize
      height: ${data.input_size.0}
      width: ${data.input_size.1}
    - type: albumentations.Normalize
    - type: albumentations.pytorch.transforms.ToTensorV2

  train_dataset:
    - ${coco_train}

  validation_dataset:
#    - ${coco_val}
    - ${transferring}
