# @package _global_
data:
  coco_train_root: D:/datasets/coco/val2017
  coco_val_root: D:/datasets/coco/val2017
  coco_annotations_root: D:/datasets/data/coco/annotations

  fsod_root: null
  fsod_annotations_root: null

  megapixel_mnist_train_root: D:/datasets/megapixel_mnist/train
  megapixel_mnist_val_root: D:/datasets/megapixel_mnist/tets
  megapixel_mnist_annotations_root: D:/datasets/megapixel_mnist/annotations


  custom_annotations_root: null
